/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

/**
 *
 * @author flora
 */
public class GUILogin extends javax.swing.JFrame {

    /**
     * Creates new form GUILogin
     */
    public GUILogin() {
        initComponents();
    }
    
    public void entrar() {
        
        /*
        if (jtfEmail.getText().equals(u.getEmail()) && jtfSenha.getText().equals(u.getSenha())) {
        GUIDash d = new GUIDash();
        jDesktopPrincipal.add(d);
        d.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Login e/ou senha incorreto(s)", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        */
        GUIDash d = new GUIDash();
        
        jDesktopPrincipal.add(d);
        d.setVisible(true);
    }
        
    public void cadastrar() {
        GUICadastro c = new GUICadastro();
        jDesktopPrincipal.add(c);
        c.setVisible(true);
    }
      public void fecharAplicacao() {
        System.exit(1);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPrincipal = new javax.swing.JPanel();
        jlEmail = new javax.swing.JLabel();
        jlSenha = new javax.swing.JLabel();
        jtfSenha = new javax.swing.JTextField();
        jlLogin = new javax.swing.JLabel();
        jtfEmail = new javax.swing.JTextField();
        jbRecuperarSenha = new javax.swing.JButton();
        jbCadastrar = new javax.swing.JButton();
        jlFacebook = new javax.swing.JLabel();
        jlGoogle = new javax.swing.JLabel();
        jlFecharAplicacao = new javax.swing.JLabel();
        jlLogar = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPrincipal.setBackground(new java.awt.Color(199, 212, 219));

        jlEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlEmail.setText("Email");

        jlSenha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlSenha.setText("Senha");

        jtfSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtfSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfSenhaActionPerformed(evt);
            }
        });

        jlLogin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlLogin.setText("Login");

        jtfEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfEmailActionPerformed(evt);
            }
        });

        jbRecuperarSenha.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jbRecuperarSenha.setText("Esqueci minha senha");

        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });

        jlFacebook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/facebook.png"))); // NOI18N

        jlGoogle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/google.png"))); // NOI18N

        jlFecharAplicacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Fechar.png"))); // NOI18N
        jlFecharAplicacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlFecharAplicacaoMouseClicked(evt);
            }
        });

        jlLogar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ok.png"))); // NOI18N
        jlLogar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlLogarMouseClicked(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPrincipalLayout = new javax.swing.GroupLayout(jDesktopPrincipal);
        jDesktopPrincipal.setLayout(jDesktopPrincipalLayout);
        jDesktopPrincipalLayout.setHorizontalGroup(
            jDesktopPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPrincipalLayout.createSequentialGroup()
                .addGroup(jDesktopPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(210, 210, 210)
                        .addComponent(jlLogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlFecharAplicacao))
                    .addGroup(jDesktopPrincipalLayout.createSequentialGroup()
                        .addGroup(jDesktopPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPrincipalLayout.createSequentialGroup()
                                .addGap(153, 153, 153)
                                .addGroup(jDesktopPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlEmail)
                                    .addComponent(jlSenha))
                                .addGroup(jDesktopPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jDesktopPrincipalLayout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addGroup(jDesktopPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jbRecuperarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jbCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jDesktopPrincipalLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jDesktopPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jDesktopPrincipalLayout.createSequentialGroup()
                                .addGap(264, 264, 264)
                                .addComponent(jlFacebook)
                                .addGap(35, 35, 35)
                                .addComponent(jlGoogle)))
                        .addGap(0, 202, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jDesktopPrincipalLayout.createSequentialGroup()
                .addGap(305, 305, 305)
                .addComponent(jlLogar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDesktopPrincipalLayout.setVerticalGroup(
            jDesktopPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPrincipalLayout.createSequentialGroup()
                        .addGroup(jDesktopPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlLogin)
                            .addComponent(jButton1))
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlEmail)
                            .addComponent(jtfEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jDesktopPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlSenha)
                            .addComponent(jtfSenha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbRecuperarSenha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlLogar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addGroup(jDesktopPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlFacebook)
                            .addComponent(jlGoogle))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbCadastrar)
                        .addContainerGap(69, Short.MAX_VALUE))
                    .addGroup(jDesktopPrincipalLayout.createSequentialGroup()
                        .addComponent(jlFecharAplicacao)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfSenhaActionPerformed

    private void jtfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfEmailActionPerformed

    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        cadastrar();
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jlFecharAplicacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlFecharAplicacaoMouseClicked
        fecharAplicacao();
    }//GEN-LAST:event_jlFecharAplicacaoMouseClicked

    private void jlLogarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlLogarMouseClicked
        entrar();
    }//GEN-LAST:event_jlLogarMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        GUITarefa t = new GUITarefa();
        jDesktopPrincipal.add(t);
        t.setVisible(true);
        t.preencherTabela();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUILogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jDesktopPrincipal;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbRecuperarSenha;
    private javax.swing.JLabel jlEmail;
    private javax.swing.JLabel jlFacebook;
    private javax.swing.JLabel jlFecharAplicacao;
    private javax.swing.JLabel jlGoogle;
    private javax.swing.JLabel jlLogar;
    private javax.swing.JLabel jlLogin;
    private javax.swing.JLabel jlSenha;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfSenha;
    // End of variables declaration//GEN-END:variables
}
